name: Test with TeXLive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vvakame/review
    steps:
    - uses: actions/checkout@v2
    - name: Build and test with Rake
      run: |
        gem install bundler --no-document
        bundle install --retry 3
        bundle exec rake
