name: Test with TeXLive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vvakame/review
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: fix ImageMagick policy.xml on Linux
      run: sudo sed -i 's/none/read|write/g' /etc/ImageMagick-6/policy.xml
    - name: Build and test with Rake
      run: |
        gem install bundler --no-document
        bundle install --retry 3
        bundle exec rake
